# Generated by Django 4.2.6 on 2023-10-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinePatterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_thread', models.CharField(max_length=35)),
                ('line_pattern', models.CharField(default='[]', max_length=9999)),
            ],
        ),
    ]
